---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
   - port: 80
     targetPort: 8080
  selector:
    service: ambassador
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: app
spec:
  prefix: /app/
  service: app:3000
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: auth
spec:
  prefix: /auth/
  service: auth:8080
---
apiVersion: getambassador.io/v1
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: "auth:8080"
  allowed_request_headers:
  - "X-Auth-Token"
  allowed_authorization_headers:
  - "X-Auth-Token"
  - "X-User-Id"
  - "X-Service"